### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [dech0n/hobby-hub#12]
Hello! 

I am reviewing all group wikis today and wanted to drop a few things here that I would like y'all to take care of.

## Feature List
- [x] You can remove the references to the app you cloned "[books]".

## Schema
- [x] Add your schema to your wiki, either by embedding an image of your DB diagram or by writing out your tables in markdown tables.

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by IrinaAmzashvili** [comment]
All done. Thank you for the feedback!

https://github.com/dech0n/hobby-hub/wiki/Database-Schema
https://github.com/dech0n/hobby-hub/wiki/Feature-List
